### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by oltip** [goru001/nlp-for-punjabi#1]
Hi there, 

First of all, congratulations for your job. 
I was wondering which language model architecture did you use. Is it the AWD_LSTM?

**Comment by goru001** [comment]
Thank you for the appreciation. Yes, the architecture is AWD_LSTM.

**Comment by goru001** [comment]
I'm closing this issue, feel free to reopen if there's anything!

**Comment by oltip** [comment]
No, no, it's ok. Thank you for your reply. Yeah, I was looking at the code, and realized that the first versions of fastai didn't require to specify the architecture as it was the only one.
